"""FastAPI entry point for the AI Learning Companion backend.

Endpoints:
- GET /health             provider, adapter, and speech readiness
- GET /schema             expose primitives.json so the frontend can validate
- POST /lesson            multipart PNG -> SSE stream of token/primitive events
- POST /assess            grade a checkpoint and adapt the learner model
- POST /chat              text chat with the active tutor model
- POST /transcribe        local Whisper speech-to-text for chat input
- GET/POST /speech        list voices / synthesize local Kokoro speech
- GET /learner/{user_id}  return the per-user knowledge profile
"""
from __future__ import annotations

import json
import hashlib
import os
import asyncio
import tempfile
from contextlib import asynccontextmanager
from contextlib import suppress
from pathlib import Path
from typing import Literal

API_ROOT = Path(__file__).resolve().parent
SCHEMA_PATH = API_ROOT.parent / "schema" / "primitives.json"


def _load_env_file() -> None:
    """Tiny zero-dep .env loader so judges only need to fill `.env` and run.

    Looks for `<repo-root>/.env` first, then `<api>/.env`. Skips lines that
    are blank, comments, or already exported in the process environment so
    explicit shell `set FOO=bar` overrides take precedence.
    """
    candidates = [API_ROOT.parent / ".env", API_ROOT / ".env"]
    for path in candidates:
        if not path.exists():
            continue
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                s = line.strip()
                if not s or s.startswith("#") or "=" not in s:
                    continue
                k, _, v = s.partition("=")
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                if k and k not in os.environ:
                    os.environ[k] = v
        except OSError:
            pass


_load_env_file()
DEFAULT_MODEL_CHOICE = "openai" if os.environ.get("OPENAI_API_KEY", "").strip() else "edge"

from fastapi import FastAPI, File, Form, HTTPException, Response, UploadFile  # noqa: E402
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402
from pydantic import BaseModel, Field  # noqa: E402
from sse_starlette.sse import EventSourceResponse  # noqa: E402

from learner import LearnerStore, normalise_evidence  # noqa: E402
from speech import DEFAULT_VOICE, SpeechError, get_speech_engine  # noqa: E402
from transcription import TranscriptionError, get_transcriber  # noqa: E402
from teacher import (  # noqa: E402
    MODEL_REGISTRY,
    OllamaTeacher,
    Teacher,
    TeacherError,
    resolve_teacher,
)
from parser import IncrementalTagParser  # noqa: E402
from salvage import salvage_raw_to_primitives  # noqa: E402
from validator import validate_and_repair  # noqa: E402

@asynccontextmanager
async def _lifespan(_app: FastAPI):
    """Warm local inference without making a billable cloud request."""
    try:
        get_teacher("edge").warmup()
    except Exception as exc:
        print(f"[warmup] non-fatal: {exc}")
    warm_task: asyncio.Task | None = None
    speech = get_speech_engine()
    prefetch_setting = os.environ.get("SPEECH_PREFETCH", "auto").lower()
    if (
        prefetch_setting not in {"0", "false", "no"}
        and speech.available
        and speech.lock_path.exists()
    ):
        async def _warm_speech() -> None:
            try:
                await speech.prefetch()
            except Exception as exc:
                print(f"[speech-prefetch] non-fatal: {exc}")

        # Do not delay API readiness while ONNX/G2P assets load on CPU.
        warm_task = asyncio.create_task(_warm_speech())
    try:
        yield
    finally:
        if warm_task and not warm_task.done():
            warm_task.cancel()
            with suppress(asyncio.CancelledError):
                await warm_task


app = FastAPI(title="Y API", version="0.2.0", lifespan=_lifespan)

_cors_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
_extra_cors = os.environ.get("CORS_ORIGINS", "").strip()
if _extra_cors:
    _cors_origins.extend(o.strip() for o in _extra_cors.split(",") if o.strip())

app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_learner_store: LearnerStore | None = None


def _safety_identifier(user_id: str) -> str:
    salt = os.environ.get("SAFETY_ID_SALT", "y-local-demo")
    return "y_" + hashlib.sha256(f"{salt}|{user_id}".encode("utf-8")).hexdigest()[:24]


def _deterministic_checkpoint(
    state: dict,
    conversation_id: str,
    preferred_concepts: list[str] | None = None,
) -> dict:
    """Build a useful local checkpoint without another full LLM decode.

    The lesson has already been generated by the teacher. On the local edge
    path a second Gemma vision/text turn made the toolbar stay busy long after
    the answer was visible. The checkpoint remains personalized by the newly
    extracted concepts and learner uncertainty, while cloud teachers may still
    use their structured checkpoint generator.
    """
    concepts = [str(item) for item in (preferred_concepts or []) if item][:2]
    if not concepts:
        concepts = [
            str(item.get("name"))
            for item in state.get("concept_beliefs", [])[:2]
            if isinstance(item, dict) and item.get("name")
        ]
    label = concepts[0].replace("-", " ") if concepts else "the lesson's main idea"
    return {
        "conversation_id": conversation_id,
        "question": f"Solve a fresh example using {label}, then explain why your method works.",
        "concepts": concepts or ["lesson transfer"],
        "rubric": "Check the method, result, and whether the explanation is independent.",
        "difficulty": "introductory",
    }


def get_teacher(model_choice: str = DEFAULT_MODEL_CHOICE) -> Teacher:
    """Return the cached Teacher matching the toolbar's `model_choice`.

    Defaults to the edge baseline so /health and warmup never need to know
    about the user's selection.
    """
    return resolve_teacher(model_choice)


def get_learner_store() -> LearnerStore:
    global _learner_store
    if _learner_store is None:
        _learner_store = LearnerStore()
    return _learner_store


@app.get("/health")
async def health() -> dict:
    """Liveness + per-model readiness for the toolbar.

    The Ollama daemon is socket-pinged with a 1s timeout. Each ping runs in
    a worker thread via ``asyncio.to_thread`` so the registry's three
    readiness probes don't serialise on /health.
    """
    import asyncio as _asyncio

    edge = get_teacher("edge")
    is_ollama = isinstance(edge, OllamaTeacher)

    async def _ready(choice: str) -> bool:
        try:
            t = get_teacher(choice)
            return bool(await _asyncio.to_thread(t.ping))
        except Exception:
            return False

    choices = list(MODEL_REGISTRY.keys())
    flags = await _asyncio.gather(*(_ready(c) for c in choices))
    ready_by_choice = dict(zip(choices, flags))
    edge_ready = ready_by_choice.get("edge", False) if is_ollama else False

    return {
        "status": "ok",
        "ollama_host": edge.host if is_ollama else "",
        "model": edge.model,
        "ollama_reachable": edge_ready,
        "schema_exists": SCHEMA_PATH.exists(),
        "preferred_model": "openai" if ready_by_choice.get("openai") else "edge",
        "models": {
            choice: {
                "kind": cfg["kind"],
                "model": cfg["model"],
                "ready": ready_by_choice.get(choice, False),
            }
            for choice, cfg in MODEL_REGISTRY.items()
        },
        "learner_adapter": get_learner_store().adapter_info,
        "speech": get_speech_engine().health(),
        "transcription": get_transcriber().health(),
    }


@app.get("/schema")
async def schema() -> dict:
    """Expose the primitive schema so the frontend can validate against the same source of truth."""
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


@app.post("/lesson")
async def lesson(
    image: UploadFile = File(...),
    teacher_mode: bool = Form(False),
    user_id: str = Form("anon"),
    conversation_id: str = Form("default"),
    model_choice: str = Form(DEFAULT_MODEL_CHOICE),
):
    """Accept a canvas PNG and stream lesson events.

    Form fields:
      - image          (required, PNG): the canvas snapshot
      - teacher_mode   (bool, default False): if true, fire a second Gemma call
                       after the lesson stream completes, asking for educator
                       JSON (misconceptions / follow_ups / prereqs / difficulty)
                       streamed as a single `educator_notes` event.
      - user_id        (str, default 'anon'): stable per-browser identifier
                       used by the learner module to track mastery across
                       sessions.
      - conversation_id (str): binds checkpoints to the active browser session.
      - model_choice   (str, defaults to OpenAI when configured): one of 'openai' (GPT-5.6),
                       'edge' (gemma4:e4b),
                       'edge-ft' (the fine-tuned y-gemma4 LoRA-merged GGUF),
                       or 'cloud' (Gemma-4-31B via Google AI Studio). Honoured
                       even if the chosen backend isn't running -- the call
                       will surface a clear error event in that case.

    SSE event types:
      - "token":           {"text": "..."}                free narrative tokens
      - "primitive":       {"tag": "box", "args": {...}}  validated tag
      - "generation_complete": {}                           model answer is fully streamed
      - "educator_notes":  {misconceptions, follow_ups, prereqs, difficulty}
      - "learner_update":  {topic, concepts_seen, mastered, struggling, ...}
      - "done":            {"reason": "..."}              terminal event
      - "error":           {"message": "..."}             terminal error
    """
    png_bytes = await image.read()
    teacher = get_teacher(model_choice)
    learner = get_learner_store()
    parser = IncrementalTagParser()
    primitives_count = 0
    safety_identifier = _safety_identifier(user_id)
    # Pull the learner's mastery prefix (if any) and prepend it to the
    # system prompt for THIS lesson only. The teacher object's base prompt
    # is left untouched so concurrent calls don't bleed into each other.
    mastery_prefix = learner.system_prompt_prefix(user_id)

    async def event_stream():
        # Accumulate the parsed lesson text so the educator-notes + learner
        # calls can condition on what the tutor actually said.
        nonlocal primitives_count
        lesson_chunks: list[str] = []
        try:
            async for token in teacher.stream_lesson(
                png_bytes,
                system_prefix=mastery_prefix,
                safety_identifier=safety_identifier,
            ):
                lesson_chunks.append(token)
                for evt in parser.feed(token):
                    if evt["event"] == "token":
                        yield {"event": "token", "data": json.dumps({"text": evt["text"]})}
                    elif evt["event"] == "primitive":
                        ok, fixed_tag = validate_and_repair(evt["tag"])
                        if ok:
                            primitives_count += 1
                            yield {"event": "primitive", "data": json.dumps(fixed_tag)}
                        else:
                            yield {
                                "event": "token",
                                "data": json.dumps(
                                    {"text": fixed_tag.get("args", {}).get("content", "")}
                                ),
                            }
            for evt in parser.flush():
                if evt["event"] == "token":
                    yield {"event": "token", "data": json.dumps({"text": evt["text"]})}
                elif evt["event"] == "primitive":
                    ok, fixed_tag = validate_and_repair(evt["tag"])
                    if ok:
                        primitives_count += 1
                        yield {"event": "primitive", "data": json.dumps(fixed_tag)}

            # Last-resort salvage: if the parser produced 0 primitives the
            # model ignored the tag protocol entirely (common with the small
            # gemma4:e4b baseline). Synthesise primitives from the raw text
            # so the whiteboard still draws something.
            if primitives_count == 0 and lesson_chunks:
                raw_text = "".join(lesson_chunks)
                for synth in salvage_raw_to_primitives(raw_text):
                    primitives_count += 1
                    yield {"event": "primitive", "data": json.dumps(synth)}

            # The expensive learner extraction/checkpoint work below should
            # never keep the already-complete whiteboard answer locked. The
            # frontend drains its drawing queue and releases the toolbar here.
            yield {"event": "generation_complete", "data": "{}"}

            if teacher_mode:
                try:
                    notes = await teacher.educator_notes(
                        png_bytes, lesson_text="".join(lesson_chunks)
                    )
                    yield {"event": "educator_notes", "data": json.dumps(notes)}
                except Exception as exc:
                    # Educator notes are advisory; never fail the lesson over them.
                    yield {
                        "event": "educator_notes",
                        "data": json.dumps({
                            "misconceptions": [], "follow_ups": [],
                            "prereqs": [], "difficulty": "",
                            "error": f"educator notes failed: {exc}",
                        }),
                    }

            # Update the learner profile after the lesson completes. This is
            # advisory and runs inline (not background) so the SSE stream
            # surfaces the new session record before "done", letting the
            # learner panel light up immediately.
            #
            # The extractor model is ALWAYS the local edge model: when the
            # active teacher is cloud, we still want the learner panel to
            # update with a fast/free local extraction (no extra API spend
            # per session).
            extractor_model = get_teacher("edge").model
            try:
                rec = await learner.update(
                    user_id=user_id,
                    lesson_text="".join(lesson_chunks),
                    primitives_count=primitives_count,
                    teacher_model=extractor_model,
                    conversation_id=conversation_id,
                )
                # Don't push the legacy raw session embedding through SSE; the
                # panel fetches the probabilistic state from /learner/{user_id}.
                payload = {k: v for k, v in rec.__dict__.items() if k != "embedding"}
                payload["has_embedding"] = bool(rec.embedding)
                yield {"event": "learner_update", "data": json.dumps(payload)}
                profile = learner.get(user_id)
                state = profile.last_state or learner.state_snapshot(profile)

                if model_choice in {"edge", "edge-ft"}:
                    checkpoint_raw = _deterministic_checkpoint(
                        state,
                        conversation_id,
                        rec.concepts_seen,
                    )
                else:
                    try:
                        checkpoint_raw = await teacher.generate_checkpoint(
                            lesson_text="".join(lesson_chunks),
                            learner_state=state,
                            conversation_id=conversation_id,
                            safety_identifier=safety_identifier,
                        )
                    except Exception:
                        checkpoint_raw = _deterministic_checkpoint(
                            state,
                            conversation_id,
                            rec.concepts_seen,
                        )
                if not rec.concepts_seen and checkpoint_raw.get("concepts"):
                    weak_evidence = normalise_evidence(
                        {
                            "concepts": checkpoint_raw.get("concepts", []),
                            "outcome": {"correct": 0.2, "partial": 0.5, "incorrect": 0.3},
                            "independence": 0.2,
                            "evidence_strength": 0.15,
                            "response_summary": "Concept inferred from the generated checkpoint; answer not yet assessed.",
                            "task_text": "".join(lesson_chunks)[:1000],
                        },
                        user_id=user_id,
                        conversation_id=conversation_id,
                        source="help_request",
                    )
                    state, _ = await learner.record_evidence(
                        weak_evidence,
                        allow_adaptation=False,
                    )
                yield {"event": "learner_state", "data": json.dumps(state)}
                checkpoint = learner.save_checkpoint(user_id, checkpoint_raw)
                yield {"event": "checkpoint", "data": json.dumps(checkpoint)}
            except Exception as exc:
                yield {
                    "event": "learner_update",
                    "data": json.dumps({"error": f"learner update failed: {exc}"}),
                }

            yield {"event": "done", "data": json.dumps({"reason": "completed"})}
        except TeacherError as exc:
            yield {"event": "error", "data": json.dumps({"message": str(exc)})}
        except Exception as exc:
            yield {"event": "error", "data": json.dumps({"message": f"internal: {exc}"})}

    return EventSourceResponse(event_stream())


@app.post("/assess")
async def assess(
    image: UploadFile = File(...),
    user_id: str = Form("anon"),
    conversation_id: str = Form("default"),
    checkpoint_id: str = Form(...),
    model_choice: str = Form(DEFAULT_MODEL_CHOICE),
):
    """Grade a checkpoint answer, run a guarded Level-2 update, and reteach."""
    png_bytes = await image.read()
    learner = get_learner_store()
    checkpoint = learner.get_checkpoint(user_id, checkpoint_id)
    if checkpoint is None:
        raise HTTPException(status_code=404, detail="checkpoint not found for this learner")
    if checkpoint.get("conversation_id") != conversation_id:
        raise HTTPException(status_code=409, detail="checkpoint belongs to another conversation")
    teacher = get_teacher(model_choice)
    safety_identifier = _safety_identifier(user_id)

    async def event_stream():
        parser = IncrementalTagParser()
        lesson_chunks: list[str] = []
        primitives_count = 0
        try:
            raw = await teacher.extract_evidence(
                png_bytes,
                checkpoint,
                safety_identifier=safety_identifier,
            )
            if isinstance(raw, dict):
                raw.setdefault("task_text", checkpoint.get("question", ""))
            evidence = normalise_evidence(
                raw,
                user_id=user_id,
                conversation_id=conversation_id,
                source="checkpoint_answer",
            )
            state, adaptation = await learner.record_evidence(
                evidence,
                allow_adaptation=True,
            )
            evidence_payload = evidence.to_dict()
            evidence_payload["adaptation"] = adaptation
            yield {"event": "evidence", "data": json.dumps(evidence_payload)}

            prefix = learner.system_prompt_prefix(user_id)
            async for token in teacher.stream_assessment_feedback(
                png_bytes,
                checkpoint,
                evidence_payload,
                system_prefix=prefix,
                safety_identifier=safety_identifier,
            ):
                lesson_chunks.append(token)
                for evt in parser.feed(token):
                    if evt["event"] == "token":
                        yield {"event": "token", "data": json.dumps({"text": evt["text"]})}
                    elif evt["event"] == "primitive":
                        ok, fixed_tag = validate_and_repair(evt["tag"])
                        if ok:
                            primitives_count += 1
                            yield {"event": "primitive", "data": json.dumps(fixed_tag)}
            for evt in parser.flush():
                if evt["event"] == "token":
                    yield {"event": "token", "data": json.dumps({"text": evt["text"]})}
                elif evt["event"] == "primitive":
                    ok, fixed_tag = validate_and_repair(evt["tag"])
                    if ok:
                        primitives_count += 1
                        yield {"event": "primitive", "data": json.dumps(fixed_tag)}
            if primitives_count == 0 and lesson_chunks:
                for primitive in salvage_raw_to_primitives("".join(lesson_chunks)):
                    primitives_count += 1
                    yield {"event": "primitive", "data": json.dumps(primitive)}

            yield {"event": "learner_state", "data": json.dumps(state)}
            try:
                next_raw = await teacher.generate_checkpoint(
                    lesson_text="".join(lesson_chunks) or evidence.response_summary,
                    learner_state=state,
                    conversation_id=conversation_id,
                    safety_identifier=safety_identifier,
                )
            except Exception:
                concept = evidence.concepts[0].name if evidence.concepts else "the same idea"
                next_raw = {
                    "conversation_id": conversation_id,
                    "question": f"Try a new example using {concept}. Show each step and explain why it works.",
                    "concepts": [concept],
                    "rubric": "The answer applies the target concept correctly and explains the reasoning.",
                    "difficulty": "transfer" if evidence.outcome.correct >= 0.7 else "introductory",
                }
            next_checkpoint = learner.save_checkpoint(user_id, next_raw)
            yield {"event": "checkpoint", "data": json.dumps(next_checkpoint)}

            # Fast self-improvement loop: when the answer shows a struggle,
            # distil one durable teaching heuristic for this concept so future
            # lessons on it avoid the same pitfall. It runs on the edge model
            # after the visible feedback/checkpoint, and never fails the assess.
            try:
                if evidence.concepts and (
                    evidence.outcome.soft_score < 0.75 or evidence.misconception
                ):
                    heuristic = await learner.reflect(
                        evidence,
                        checkpoint,
                        get_teacher("edge").model,
                    )
                    if heuristic:
                        learner.save_heuristic(
                            user_id=user_id,
                            concepts=[c.name for c in evidence.concepts],
                            text=heuristic,
                            source_evidence_id=evidence.evidence_id,
                        )
            except Exception:
                pass

            yield {"event": "done", "data": json.dumps({"reason": "assessed"})}
        except TeacherError as exc:
            yield {"event": "error", "data": json.dumps({"message": str(exc)})}
        except Exception as exc:
            yield {"event": "error", "data": json.dumps({"message": f"internal: {exc}"})}

    return EventSourceResponse(event_stream())


@app.get("/learner/{user_id}")
async def learner_profile(user_id: str) -> dict:
    """Return the per-user knowledge profile.

    Includes legacy sessions plus v2 evidence, open-vocabulary beliefs,
    latent trajectory, checkpoint history, online steps, and rollbacks.
    """
    store = get_learner_store()
    profile = store.get(user_id)
    state = profile.last_state or store.state_snapshot(profile)
    return {
        **profile.to_dict(),
        "mastery_summary": profile.mastery_summary(),
        "learner_state": state,
        "concept_beliefs": state.get("concept_beliefs", []),
        "latent_trajectory": state.get("latent_trajectory", []),
        "adapter_version": profile.adapter.get("base_version"),
        "online_step_count": profile.adapter.get("online_steps", 0),
        "rollback_count": profile.adapter.get("rollback_count", 0),
    }


@app.delete("/learner/{user_id}")
async def reset_learner(user_id: str) -> dict:
    """Wipe a learner profile (useful during demo recording).

    Returns 200 even if the file didn't exist.
    """
    store = get_learner_store()
    try:
        store.reset(user_id)
    except OSError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return {"ok": True}


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=8000)


class ChatRequest(BaseModel):
    messages: list[ChatMessage] = Field(min_length=1, max_length=32)
    user_id: str = Field(default="anon", max_length=160)
    conversation_id: str = Field(default="default", max_length=160)
    model_choice: str = Field(default=DEFAULT_MODEL_CHOICE, max_length=40)
    lesson_context: str = Field(default="", max_length=20000)


@app.post("/chat")
async def chat(request: ChatRequest):
    """Stream a Markdown tutoring reply without mutating learner mastery."""
    if request.messages[-1].role != "user":
        raise HTTPException(status_code=422, detail="the final chat message must be from the learner")
    teacher = get_teacher(request.model_choice)
    learner = get_learner_store()
    profile = learner.get(request.user_id)
    state = profile.last_state or learner.state_snapshot(profile)
    learner_context = str(state.get("profile_text", ""))
    messages = [message.model_dump() for message in request.messages]

    async def event_stream():
        try:
            async for delta in teacher.stream_chat(
                messages,
                learner_context=learner_context,
                lesson_context=request.lesson_context,
                safety_identifier=_safety_identifier(request.user_id),
            ):
                yield {"event": "delta", "data": json.dumps({"text": delta})}
            yield {"event": "done", "data": json.dumps({"reason": "completed"})}
        except TeacherError as exc:
            yield {"event": "error", "data": json.dumps({"message": str(exc)})}
        except Exception as exc:
            yield {"event": "error", "data": json.dumps({"message": f"internal: {exc}"})}

    return EventSourceResponse(event_stream())


_AUDIO_SUFFIXES = {
    "audio/wav": ".wav",
    "audio/x-wav": ".wav",
}
_MAX_AUDIO_BYTES = 12 * 1024 * 1024


@app.post("/transcribe")
async def transcribe(audio: UploadFile = File(...)) -> dict:
    """Transcribe one short microphone recording through local Whisper."""
    content_type = (audio.content_type or "").split(";", 1)[0].lower()
    if content_type not in _AUDIO_SUFFIXES:
        raise HTTPException(status_code=415, detail="unsupported audio format")
    transcriber = get_transcriber()
    if not transcriber.available:
        raise HTTPException(
            status_code=503,
            detail="Local transcription is not installed. Run `uv sync --extra stt` in api.",
        )
    payload = await audio.read(_MAX_AUDIO_BYTES + 1)
    if not payload:
        raise HTTPException(status_code=400, detail="empty audio recording")
    if len(payload) > _MAX_AUDIO_BYTES:
        raise HTTPException(status_code=413, detail="audio recording exceeds 12 MB")

    path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=_AUDIO_SUFFIXES[content_type]) as tmp:
            tmp.write(payload)
            path = Path(tmp.name)
        result = await transcriber.transcribe(path)
        if not result.get("text"):
            raise HTTPException(status_code=422, detail="no speech detected")
        return result
    except TranscriptionError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    finally:
        if path is not None:
            path.unlink(missing_ok=True)


class SpeechRequest(BaseModel):
    text: str = Field(min_length=1, max_length=500)
    voice: str = DEFAULT_VOICE
    speed: float = Field(default=1.0, ge=0.8, le=1.2)


@app.get("/speech/voices")
async def speech_voices() -> dict:
    engine = get_speech_engine()
    return {
        "voices": engine.voices(),
        "available": engine.available,
        "model_version": engine.health()["model_version"],
    }


@app.post("/speech")
async def speech(request: SpeechRequest) -> Response:
    engine = get_speech_engine()
    try:
        audio, metadata = await engine.synthesize(
            request.text,
            request.voice,
            request.speed,
        )
    except SpeechError as exc:
        status = 503 if not engine.available else 422
        raise HTTPException(status_code=status, detail=str(exc)) from exc
    return Response(
        content=audio,
        media_type="audio/wav",
        headers={
            "X-Speech-Voice": str(metadata.get("voice", request.voice)),
            "X-Speech-Cache": "hit" if metadata.get("cached") else "miss",
            "X-Speech-Model": str(metadata.get("model_version", "")),
        },
    )
